config/routes.rb
Rails.application.routes.draw do
  resources :welcomes
  root 'welcomes#index'

end

app/models/welcome.rb
class Welcome < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  before_action :set_welcome, only: [:show, :edit, :update, :destroy]

  # GET /welcomes
  # GET /welcomes.json
  def index
    @welcomes = Welcome.all
  end

  # GET /welcomes/1
  # GET /welcomes/1.json
  def show
  end

  # GET /welcomes/new
  def new
    @welcome = Welcome.new
  end

  # GET /welcomes/1/edit
  def edit
  end

  # POST /welcomes
  # POST /welcomes.json
  def create
    @welcome = Welcome.new(welcome_params)

    respond_to do |format|
      if @welcome.save
        format.html { redirect_to @welcome, notice: 'Welcome was successfully created.' }
        format.json { render :show, status: :created, location: @welcome }
      else
        format.html { render :new }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /welcomes/1
  # PATCH/PUT /welcomes/1.json
  def update
    respond_to do |format|
      if @welcome.update(welcome_params)
        format.html { redirect_to @welcome, notice: 'Welcome was successfully updated.' }
        format.json { render :show, status: :ok, location: @welcome }
      else
        format.html { render :edit }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /welcomes/1
  # DELETE /welcomes/1.json
  def destroy
    @welcome.destroy
    respond_to do |format|
      format.html { redirect_to welcomes_url, notice: 'Welcome was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_welcome
      @welcome = Welcome.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def welcome_params
      params.fetch(:welcome, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcomes/_form.html.erb
<%= form_for(@welcome) do |f| %>
  <% if @welcome.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@welcome.errors.count, "error") %> prohibited this welcome from being saved:</h2>

      <ul>
      <% @welcome.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/welcomes/edit.html.erb
<h1>Editing Welcome</h1>

<%= render 'form' %>

<%= link_to 'Show', @welcome %> |
<%= link_to 'Back', welcomes_path %>

app/views/welcomes/index.html.erb
<style>
  .box-shadow {
    box-shadow: 0 10px 30px rgba(18,20,22,0.25);
  }
  .list-style-none {
    list-style: none;
  }
  .padding {
    padding: 10rem 5rem;
  }
  .font-large {
    font-size: 2rem;
  }
  .white {
    color: #fff;
  }
  .background-blue-dark-2 {
    background: url(https://sumome.com/images/dohyo/home-intro-bg.jpg) no-repeat center center;
  }
  .margin-none {
    margin: 0 !important;
  }
  #home-checks .check {
    width: 22px;
    height: auto;
    position: relative;
    top: -2%;
    margin-right: 4px;
  }
  /*FEATURES*/
  .icon {
    padding-bottom: 20px;
    background-repeat: no-repeat;
    padding-left: 65px;
  }
  .header {
      text-align: center;
      margin-bottom: 100px;
      padding: 0 0 45px;
  }
  .signup_btn {
    background-color: transparent;
    border-color: white;
    color: #fff;
    position: relative;
    display: inline-block;
    border: 2px solid;
    padding:15px 42px 15px;
    height: 50px;
    width: 200px;
    border-radius: 5px;
    text-decoration: none;
    font-size: 12px;
    letter-spacing: 0.05em;
    font-weight: 700;
    text-transform: uppercase;
    -webkit-transition: all .5s ease-out;
         -o-transition: all .5s ease-out;
            transition: all .5s ease-out;
  }
  .signup_btn:hover {
    border-color: #09c;
    background-color: #09c;
    color: #fff;
    text-decoration: none;
  }
  .btn:hover {
    border-color: #09c;
    background-color: #09c;
  }
</style> <!--videoscreensharing-->

<head>
  <title>ThinkRTC | Screensharing</title>
</head>
<meta name="viewport" content="width=device-width; initial-scale = 1.0; maximum-scale=1.0; user-scalable=no" />


<!-- Home -->
<main id="home" class="masthead-video masked">
  <!--<video class="video" autoplay="" loop="" muted="">-->
  <!--    <source src="https://d3hjue7omxs01q.cloudfront.net/Video/overview/voice-video.mp4" type="video/mp4">-->
  <!--    <source src="video/video.webm" type="video/webm">-->
  <!--</video>-->
  <div class="opener rel-1">
    <div class="container">
      <div class="row">
        <center>
        <div class="lead col-lg-6" style="float:none">
          <h1 class="wow fadeInDown">Instant video meetings with clients</h1>
          <p class="lead-text">It’s very easy to deal  instantly with your customer rather than booking a meeting and waiting for other partners to make decision. </p>
        </div>
        <br>
        <div class="lead-controls">
          <div class="row-fields row">
            <div>
              <a href="/sign_up" class="btn signup_btn hvr-grow">try it now</a>
            </div>
          </div>
        </div>
        </center>
      </div>
    </div>
  </div>
</main>
  
            <header class="header" style="padding: 0px; margin-bottom: 0px">-->
          <h2>Communicate with clients using live video chat to securely conduct meetings and screen sharing. </h2>
        </header>

  
  <section id="features1" class="features section">
    <div class="container">
      <div class="row-columns row-padding row">  
        <div class="col-feature-img column col-md-6 text-center wow fadeInLeft"><br>
          <img style="width: 100%" src="<%= asset_path 'videomeeting'%>" alt="thinkrtc videochat">
        </div>
        <div class="col-feature column column-padding col-md-6">
          <ul class="features">
            <li class="icon">
              <h3>Live Video Chat </h3>
              <p>Provide a unique way to video chat with your customer. It’s the best way to impress and build a strong relationship with your customers.</p>
            </li>
            <li class="icon">
              <h3>Screensharing</h3>
              <p>Now it's easy to enhance your real-time communications experience by opting to see your client's screen.</p>
            </li>
            <li class="icon">
              <h3>Schedule Video Meetings</h3>
              <p>Fully scalable video chat agents can invite their clients to chat and make decisions faster.</p>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </section>
  
  <hr>
  
  <section id="features2" class="features section">
    <div class="container">
      <header class="header">
        <h2>Provide a unique way to video chat with your customer.  </h2>
        <p> Faster  manage clients efficiently and Increase your organization’s productivity by leveraging persistent 1-1 <br>or group chat with integrated drag-and-drop document sharing and screen sharing.</p>
      </header>
      <div class="row-padding row-columns row">
        <div class="col-feature-img text-center column column-padding col-md-5 col-md-push-7 wow fadeInUp">
          <!--<img class="feature-img" src="//cdn.mxpnl.com/cache/23e440f1e6c23d877fc2b9c0f98c9bb6/images/static/landing/marketing/autotrack/1x/browser1.png">-->
          <ul id="home-checks" class="background-blue-dark-2 box-shadow margin-none padding font-large white list-style-none">
            <li><img class="check" src="https://load.sumome.com/images/dohyo/check.svg" alt="thinkrtc"> <b>No</b> Coding Needed</li>
            <br>
            <li><img class="check" src="https://load.sumome.com/images/dohyo/check.svg" alt="thinkrtc"> Everywhere You Go</li>
            <br>
            <li><img class="check" src="https://load.sumome.com/images/dohyo/check.svg" alt="thinkrtc"> <b>Easy</b> To Use</li>
          </ul>
        </div>
        <div class="col-feature column column-padding col-md-7 col-md-pull-5">
          <ul class="features">
            <li class="icon">
              <h3>Increase Engagement</h3>
              <p>Interact with your customers in a more humane and helpful way by providing the right support  </p>
            </li>
            <li class="icon">
              <h3>Do It On The Go </h3>
              <p>Talk to your clients anywhere. Share files and folders with them.
.</p>
            </li>
            <li class="icon">
              <h3>Get Things Done Faster</h3>
              <p>Our fully scalable video chat software can invite their clients to chat and make decisions faster.</p>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </section>
  
  <hr>
  
  <!-- Banner -->
  <section id="banner" class="section-sm">
    <center>
      <<div class="container"><h2>Try our cloud based management software. <br>Schedule a demo with us!</h2>
        <div class=""  style="margin-top:50px">
          <a href="https://calendly.com/jonn-thinkrtc/15min" class="btn hvr-grow" style="background-color: #fff; color: #000">SCHEDULE A DEMO</a>
                    <p><strong>See if we are the right fit.</strong></p>

        </div>
    </center>
  </section>
</div>

app/views/welcomes/new.html.erb
<h1>New Welcome</h1>

<%= render 'form' %>

<%= link_to 'Back', welcomes_path %>

app/views/welcomes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_welcome_path(@welcome) %> |
<%= link_to 'Back', welcomes_path %>